amp_dtype: bf16
batch_size: 28
ckpt_dir: /notebooks/BYOS/state_dict
comet_experiment_key:
experiment_name: byos_v0
comet_optional: true
comet_project_name: init_test
compile: true
d_model: 768
dataset: deepmind/pg19
dataset_config: default
dataset_dir: /notebooks/PG-19
hf_streaming: false
hf_trust_remote_code: false
hf_text_field: text
hf_storage_block_size: 0
hf_streaming_read_max_retries: 20
hf_streaming_read_retry_interval_s: 5
hf_restart_on_stream_error: true
hf_restart_sleep_s: 5
hf_max_restarts: 0
hf_shuffle_buffer: 10000
hf_val_shuffle_buffer: 0
hf_token_buffer_size: 2000000
hf_prefill_tokens: 500000
hf_refresh_tokens: 50000
hf_max_doc_tokens: 0
hf_add_eos: true
hf_max_train_items: 0
hf_max_val_items: 0
device: auto
eval_every: 500
eval_fixed: true
eval_steps: 50
h_len: [0, 2048]
log_every: 50
lr: 2e-4
label_smoothing: 0.0
attn_drop: 0.0
ffn_drop: 0.0
routing_temp: 1.0
max_grad_norm: 1.0
max_train_files: 0
max_train_items: 4000
max_val_files: 0
max_val_items: 500
min_lr: 2e-5
n_heads: 12
n_layers: 12
n_local: 1024
n_state: 96
non_stop: true
num_workers: 10
pin_memory: true
resume_path: /notebooks/BYOS/state_dict/init_test_byos_v0_latest.pt
save_best: false
save_freq: 500
save_n_store: 1
seed: 67
steps: 20000
text_path:
tokenizer: sentencepiece
tokens_per_step: 262144
train_split: train
val_ratio: 0.05
val_split: validation
warmup_steps: 1000
weight_decay: 0.1
